import React from 'react';
import ReactDOM from 'react-dom/client';
import { Amplify } from 'aws-amplify';
import awsExports from './aws-exports'; // auto-generated by Amplify CLI or manually created
import './index.css'; // optional global stylesheet
import LandingPage from './components/LandingPage';

Amplify.configure(awsExports);

const container = document.getElementById('root') as HTMLElement;
const root = ReactDOM.createRoot(container);

root.render(
  <React.StrictMode>
    <AdminPanel />
  </React.StrictMode>
);
